# Site settings
title: Vaquero - Drive your Cloud Cattle
email:
description: > # this means to ignore newlines until "baseurl:"
  Vaquero is a tool to rapidly, repeatabily and reliably create your
  cloud instances from simple definiton files.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.vaquero.io" # the base hostname & protocol for your site
twitter_username: vaquero_io
github_username:  vaquero-io

# Build settings
markdown: kramdown
